export enum OperationLogAction {
  TARGET_PERCENTAGE_CHANGE = "target_percentage_change",
  ASSET_CLASS_CREATED = "asset_class_created",
  ASSET_CLASS_UPDATED = "asset_class_updated",
  ASSET_CLASS_DELETED = "asset_class_deleted",
  ASSET_TYPE_CREATED = "asset_type_created",
  ASSET_TYPE_UPDATED = "asset_type_updated",
  ASSET_TYPE_DELETED = "asset_type_deleted",
  INSTITUTION_CREATED = "institution_created",
  INSTITUTION_UPDATED = "institution_updated",
  INSTITUTION_DELETED = "institution_deleted",
  LINK_ADDED = "link_added",
  LINK_REVOKED = "link_revoked",
  AUTONOMY_GRANTED = "autonomy_granted",
  AUTONOMY_REVOKED = "autonomy_revoked",
  RISK_PROFILE_CHANGED = "risk_profile_changed",
  WEALTH_HISTORY_CREATED = "wealth_history_created",
  WEALTH_HISTORY_UPDATED = "wealth_history_updated",
  WEALTH_HISTORY_DELETED = "wealth_history_deleted",
  ASSET_MANUAL_EDIT = "asset_manual_edit",
}
